# -*- coding: utf-8 -*-
"""Melbourne_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qGYNDau9m2TG5bYPn-8IFjTV5h3yTo37
"""

!pip install scikit-learn

!pip install --upgrade scikit-learn

import pandas as pd
from sklearn.tree import DecisionTreeRegressor

melbourne_file_path = '/content/melb_data.csv'
melbourne_data = pd.read_csv(melbourne_file_path)
melbourne_data.columns

y = melbourne_data.Price

melbourne_features = ['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']

X = melbourne_data[melbourne_features]

X.describe()

X.head()

X.fillna(X.mean(), inplace=True)

melbourne_model = DecisionTreeRegressor(random_state=1)
melbourne_model.fit(X, y)

print("Making predictions for the following 5 houses")
print(X.head())
print("The predictions are")
print(melbourne_model.predict(X.head()))

